local BlockVehicles = {
    [GetHashKey('wrrs7pol')]    = { 'vippolicia.permissao' },
    [GetHashKey('SW4OAB')]   = { 'vicepresidenteoab.permissao' },
    [GetHashKey('wrksd')]   = { 'blockvehpm.permissao' },
    [GetHashKey('wrnissantitan17p')]  = { 'blockvehpm.permissao' },
    [GetHashKey('wrd35pol')]     = { 'blockvehpm.permissao' },
    [GetHashKey('wrezvani')]    = { 'blockvehpm.permissao' },
    [GetHashKey('wrrs6p')]    = { 'blockvehpm.permissao' },
    [GetHashKey('wrpsttpol')]    = { 'blockvehpm.permissao' },
    [GetHashKey('wrq8pol')]    = { 'blockvehpm.permissao' },
    [GetHashKey('wrr8pol')]    = { 'blockvehpm.permissao' },
    [GetHashKey('wrbuspol')]    = { 'blockvehpm.permissao' },
    [GetHashKey("K1200CBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KCamaroCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("K1200HospC")] = { 'owner.permissao', 'mecanico.permissao', 'hpmilitar.permissao', },
    [GetHashKey("KHeliHospC")] = { 'owner.permissao', 'mecanico.permissao', 'hpmilitar.permissao', },
    [GetHashKey("KSprinterHospC")] = { 'owner.permissao', 'mecanico.permissao', 'hpmilitar.permissao', },
    [GetHashKey("KX6HospC")] = { 'owner.permissao', 'mecanico.permissao', 'hpmilitar.permissao', },

    [GetHashKey("KAs350CBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KBlazerCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KBusCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KDinghyCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KHummerCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KJetCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KOppressorCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KRamCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KTenereCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KTrailCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },
    [GetHashKey("KSprinterCBM")] = { 'owner.permissao', 'mecanico.permissao', 'resgate.permissao', },

    [GetHashKey("KAs350SAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KBusSAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KOppressorSAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KS10SAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KSprinterSAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KTenereSAMU")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("K1200HospC")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KHeliHospC")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KSprinterHospC")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },
    [GetHashKey("KX6HospC")] = { 'owner.permissao', 'mecanico.permissao', 'hospital.permissao', },

    [GetHashKey("K1200Mec")] = { 'owner.permissao', 'mecanico.permissao' },
    [GetHashKey("KFlatMec")] = { 'owner.permissao', 'mecanico.permissao' },
    [GetHashKey("KM1Mec")] = { 'owner.permissao', 'mecanico.permissao' },
    [GetHashKey("KOppressorMec")] = { 'owner.permissao', 'mecanico.permissao' },
    [GetHashKey("KRamMec")] = { 'owner.permissao', 'mecanico.permissao' },
    [GetHashKey("KS10Mec")] = { 'owner.permissao', 'mecanico.permissao' },

    [GetHashKey("K1200Studio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },
    [GetHashKey("KMoonBeamStudio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },
    [GetHashKey("KRamStudio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },
    [GetHashKey("KUrusStudio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },
    [GetHashKey("KMinhaumStudio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },
    [GetHashKey("KRetaStudio")] = { 'owner.permissao', 'mecanico.permissao', 'tropical.permissao', },

    [GetHashKey("velardoj")] = { 'owner.permissao', 'oab.permissao' },
    [GetHashKey("swiftdoj")] = { 'owner.permissao', 'oab.permissao' },
    [GetHashKey("s1kdoj")] = { 'owner.permissao', 'oab.permissao' },
    [GetHashKey("eletrondoj")] = { 'owner.permissao', 'oab.permissao' },
}



local KidsVehicles = {
    [GetHashKey('wrcruisermini')]         = true,
    [GetHashKey('wrlamborghinikid')]       = true,
    [GetHashKey('wrminir34')]             = true,
    [GetHashKey('wrplasticcar')]          = true,
    [GetHashKey('wrrelampagomarquinhos')] = true,
    [GetHashKey('wrspiderkid')]           = true,
    [GetHashKey('wrminiporsche')]         = true,


}